# Generated by Django 5.1.1 on 2024-09-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["price"]},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_price_a33a33_idx",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_pr_price_9b1a5f_idx"),
        ),
    ]
